### ISSUE TITLE
simLine-2 write repo and service for SimCard entity class

### ISSUE THREAD

**Issue by ismoil0709** [ismoil0709/simLine#2]

**Comment by ismoil0709** [comment]
1-It is not necessary to write the create method, because the database will have pre-generated numbers
2-delete method is not needed because the numbers are never deleted we control the numbers via activity
3-Add the getAll method
4- Add the getByPlan (findAllByPlan) method and write a query for that method in the repo
that's it for now

**Comment by eeslambec** [comment]
Done!

**Comment by ismoil0709** [comment]
Good job !

**Comment by ismoil0709** [comment]
Good job!
